### ISSUE TITLE
模块 ""element-plus"" 没有导出的成员 "TabsPaneContext"。你是想改用 "import TabsPaneContext from "element-plus"" 吗?ts(2614)

### ISSUE THREAD

**Issue by lmq352489099** [element-plus/element-plus-nuxt#104]
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "start": "PORT=3001 node .output/server/index.mjs",
    "build": "nuxt build",
    "build:fat": "nuxt build --mode fat",
    "dev": "nuxt dev --port  2024 ",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "prepare": "husky install"
  },
  "dependencies": {
    "@element-plus/icons-vue": "^2.1.0",
    "@fingerprintjs/fingerprintjs": "^4.1.0",
    "crypto-js": "^4.2.0",
    "dayjs": "^1.11.10",
    "element-plus": "^2.3.4"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.0.2",
    "@commitlint/config-conventional": "^17.0.2",
    "@element-plus/nuxt": "^1.0.5",
    "@iconify-json/logos": "^1.1.33",
    "@nuxt/devtools": "^1.0.0",
    "@nuxtjs/color-mode": "^3.3.0",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@pinia/nuxt": "^0.5.1",
    "@types/crypto-js": "^4.2.1",
    "@unocss/nuxt": "^0.57.1",
    "husky": "^8.0.1",
    "nuxt": "^3.7.4",
    "pinia": "^2.1.3",
    "sass": "^1.60.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.0.4"
  }
}

**Comment by tolking** [comment]
请提供一个可以复现问题的代码片段

**Comment by tolking** [comment]
看上去 TabsPaneContext 是类型，你可以尝试更新 element-plus 到最新版并引入它
