### ISSUE TITLE
Named export 'placements' not found. The requested module '@popperjs/core' is a CommonJS module

### ISSUE THREAD

**Issue by yaowangmx** [element-plus/element-plus-nuxt#106]
Bug Type: Component

Environment
Nuxt Version: 3.11.1
Element Plus Version: 2.6.3
@element-plus/nuxt Version: 1.0.8

Steps to reproduce
本地开发正常运行，线上打包后在正式环境浏览包500

查看链接：https://www.videotowords.ai/transcript/share/39/c0141c23ea4b08a6f9a18464d424d9de

![image](https://github.com/element-plus/element-plus-nuxt/assets/17875101/98d43a7b-019a-4694-bc73-e69edd57aead)

**Comment by tolking** [comment]
[Link 10979](https://github.com/element-plus/element-plus/issues/10979)
