### ISSUE TITLE
elememt-plus 2.6.0以上编译后报 Cannot access '' before initialization

### ISSUE THREAD

**Issue by MidTin** [element-plus/element-plus-nuxt#107]
elememt-plus 2.6.0以上编译后报 Cannot access '' before initialization

**Comment by ting-xing** [comment]
同样的问题，应该是这里导致的 https://github.com/element-plus/element-plus/blob/5b25708825e3d898bae66fd1665b2d200239b45b/packages/components/config-provider/src/config-provider-props.ts#L67

**Comment by tolking** [comment]
没有复现，最好提供一个可以复现的示例

**Comment by ting-xing** [comment]
我的一个包间接依赖element-plus，它不是为 nuxt 设计的，也使用到了 ElConfigProvider，这可能是导致这个问题的原因。
在我删除间接依赖后，这个问题解决了。
奇怪的是这个问题仅在编译后出现。

**Comment by soonyh** [comment]
> 我的一个包间接依赖element-plus，它不是为 nuxt 设计的，也使用到了 ElConfigProvider，这可能是导致这个问题的原因。 在我删除间接依赖后，这个问题解决了。 奇怪的是这个问题仅在编译后出现。

![image](https://github.com/element-plus/element-plus-nuxt/assets/2361325/626df549-4a10-4d8b-9651-41e09dd2c2b3)
我也是遇到这个问题：封装了一个依赖element-plus的layer，在宿主工程中 extends，结果炸了

兄弟，解决了吗

**Comment by ting-xing** [comment]
> > 我的一个包间接依赖element-plus，它不是为 nuxt 设计的，也使用到了 ElConfigProvider，这可能是导致这个问题的原因。 在我删除间接依赖后，这个问题解决了。 奇怪的是这个问题仅在编译后出现。
> 
> ![image](https://private-user-images.githubusercontent.com/2361325/341341358-626df549-4a10-4d8b-9651-41e09dd2c2b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MzA3NDUsIm5iZiI6MTcxODkzMDQ0NSwicGF0aCI6Ii8yMzYxMzI1LzM0MTM0MTM1OC02MjZkZjU0OS00YTEwLTRkOGItOTY1MS00MWUwOWRkMmMyYjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjFUMDA0MDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUyZGVlNjEwODgxZWY1MWJkYWJmZDk1M2NjOTkwMGIzMTA2NDU2MThhM2M2NzVlNmU1ODFkZTU0ZmFjN2FkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6RrtBZb1O0yzmVuGpNGhr0NxHIdvTwCKkGd0VTBeHlk) 我也是遇到这个问题：封装了一个依赖element-plus的layer，在宿主工程中 extends，结果炸了
> 
> 兄弟，解决了吗
没有，我现在只在宿主工程里对 element-plus 有依赖，子依赖里不再依赖 element-plus

**Comment by tolking** [comment]
等下一个 element-plus 版本更新应该就可以了
