### ISSUE TITLE
Override color variables give me error

### ISSUE THREAD

**Issue by mojjjtaba** [element-plus/element-plus-nuxt#111]
I wanted to use my colors I created a file assets/scss/element-plus.scss in Nuxt 3 project. When I tried to do this I got a warning:
```
@forward 'element-plus/theme-chalk/src/common/var.scss' with (
  $colors: (
    'primary': (
      'base': #155EEF,
    ),
    'warning': (
      'base': #F79009,
    ),
    'danger': (
      'base': #F04438,
    ),
    'error': (
      'base': #F04438,
    ),
    'success': (
      'base': #12B76A,
    ),
  ),
);
```

nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    "@nuxt/test-utils/module",
    "@nuxtjs/tailwindcss",
    "@nuxtjs/google-fonts",
    "nuxt-feather-icons",
    "@element-plus/nuxt"
  ],
  css: ["~/assets/scss/main.scss"],
  googleFonts: {
    families: {
      Inter: true
    }
  },
  elementPlus: {
    importStyle: 'scss',
  },
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@use "@/assets/scss/element-plus.scss" as element;',
        },
      },
    },
  },
  app: {
    head: {
      htmlAttrs: {lang: 'es'}
    },
  }
});
```

error:
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> node_modules\element-plus\theme-chalk\src\mixins\_button.scss
160 │     font-size: $font-size;
    │     ^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> node_modules\element-plus\theme-chalk\src\button.scss
282 │ ┌         & + span {
283 │ │           margin-left: map.get($button-icon-span-gap, $size);
284 │ │         }
    │ └─── nested rule
    ╵
    node_modules\element-plus\theme-chalk\src\mixins\_button.scss 160:3  button-size()
    node_modules\element-plus\theme-chalk\src\button.scss 287:7          @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 107:7   m()
    node_modules\element-plus\theme-chalk\src\button.scss 273:5          @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 60:5    b()
    node_modules\element-plus\theme-chalk\src\button.scss 23:1           root stylesheet

Warning: 4 repetitive deprecation warnings omitted.

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules\element-plus\theme-chalk\src\mixins\_button.scss
159│     padding: $padding-vertical $padding-horizontal;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules\element-plus\theme-chalk\src\button.scss
71 │ ┌   & + & {
72 │ │     margin-left: 12px;
73 │ │   }
   │ └─── nested rule
   ╵
    node_modules\element-plus\theme-chalk\src\mixins\_button.scss 159:3  button-size()
    node_modules\element-plus\theme-chalk\src\button.scss 75:3           @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 60:5    b()
    node_modules\element-plus\theme-chalk\src\button.scss 23:1           root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules\element-plus\theme-chalk\src\mixins\_button.scss
160│     font-size: $font-size;
   │     ^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules\element-plus\theme-chalk\src\button.scss
71 │ ┌   & + & {
72 │ │     margin-left: 12px;
73 │ │   }
   │ └─── nested rule
   ╵
    node_modules\element-plus\theme-chalk\src\mixins\_button.scss 160:3  button-size()
    node_modules\element-plus\theme-chalk\src\button.scss 75:3           @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 60:5    b()
    node_modules\element-plus\theme-chalk\src\button.scss 23:1           root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules\element-plus\theme-chalk\src\mixins\_button.scss
161│     border-radius: $border-radius;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules\element-plus\theme-chalk\src\button.scss
71 │ ┌   & + & {
72 │ │     margin-left: 12px;
73 │ │   }
   │ └─── nested rule
   ╵
    node_modules\element-plus\theme-chalk\src\mixins\_button.scss 161:3  button-size()
    node_modules\element-plus\theme-chalk\src\button.scss 75:3           @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 60:5    b()
    node_modules\element-plus\theme-chalk\src\button.scss 23:1           root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> node_modules\element-plus\theme-chalk\src\mixins\_button.scss
159 │     padding: $padding-vertical $padding-horizontal;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> node_modules\element-plus\theme-chalk\src\button.scss
282 │ ┌         & + span {
283 │ │           margin-left: map.get($button-icon-span-gap, $size);
284 │ │         }
    │ └─── nested rule
    ╵
    node_modules\element-plus\theme-chalk\src\mixins\_button.scss 159:3  button-size()
    node_modules\element-plus\theme-chalk\src\button.scss 287:7          @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 107:7   m()
    node_modules\element-plus\theme-chalk\src\button.scss 273:5          @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 60:5    b()
    node_modules\element-plus\theme-chalk\src\button.scss 23:1           root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> node_modules\element-plus\theme-chalk\src\mixins\_button.scss
160 │     font-size: $font-size;
    │     ^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> node_modules\element-plus\theme-chalk\src\button.scss
282 │ ┌         & + span {
283 │ │           margin-left: map.get($button-icon-span-gap, $size);
284 │ │         }
    │ └─── nested rule
    ╵
    node_modules\element-plus\theme-chalk\src\mixins\_button.scss 160:3  button-size()
    node_modules\element-plus\theme-chalk\src\button.scss 287:7          @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 107:7   m()
    node_modules\element-plus\theme-chalk\src\button.scss 273:5          @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 60:5    b()
    node_modules\element-plus\theme-chalk\src\button.scss 23:1           root stylesheet

Warning: 4 repetitive deprecation warnings omitted.

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules\element-plus\theme-chalk\src\button-group.scss
9  │     display: inline-block;
   │     ^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules\element-plus\theme-chalk\src\mixins\utils.scss
10 │ ┌     #{$selector}::after {
11 │ │       clear: both;
12 │ │     }
   │ └─── nested rule
   ╵
    node_modules\element-plus\theme-chalk\src\button-group.scss 9:3    @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 60:5  b()
    node_modules\element-plus\theme-chalk\src\button-group.scss 7:1    root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules\element-plus\theme-chalk\src\button-group.scss
10 │     vertical-align: middle;
   │     ^^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules\element-plus\theme-chalk\src\mixins\utils.scss
10 │ ┌     #{$selector}::after {
11 │ │       clear: both;
12 │ │     }
   │ └─── nested rule
   ╵
    node_modules\element-plus\theme-chalk\src\button-group.scss 10:3   @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 60:5  b()
    node_modules\element-plus\theme-chalk\src\button-group.scss 7:1    root stylesheet

**Comment by tolking** [comment]
[link](https://github.com/element-plus/element-plus/issues/17487)
