### ISSUE TITLE
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/dayjs@1.11.12/node_modules/dayjs/dayjs.min.js?v=4385ae0a' does not provide an export named 'default' (at utils.mjs?v=4385ae0a:1:8)

### ISSUE THREAD

**Issue by vcc0827** [element-plus/element-plus-nuxt#113]
install element-plus/nuxt version 1.0.9 and comes an error: Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/dayjs@1.11.12/node_modules/dayjs/dayjs.min.js?v=4385ae0a' does not provide an export named 'default' (at utils.mjs?v=4385ae0a:1:8)

**Comment by tolking** [comment]
Can you provide a minimal example?

**Comment by vcc0827** [comment]
> Can you provide a minimal example?

1. using command build a nuxt project like: pnpm dlx nuxi@latest init demo-project
2. install element-ui/nuxt,by using command: npx nuxi@latest module add element-plus
3. add to nuxt.config.ts: 
export default defineNuxtConfig({
 modules: [
    '@element-plus/nuxt'
  ],
...other code})
4. F12 open console and see this error
<img width="380" alt="image" src="https://github.com/user-attachments/assets/2225e8f1-f35f-4d5f-92c3-aedac928886d">

**Comment by tolking** [comment]
If you are using pnpm, you may need to add an additional file. [refer to](https://github.com/element-plus/element-plus-nuxt-starter/blob/main/.npmrc)

// .npmrc

```
shamefully-hoist=true
```

then `pnpm i`

**Comment by hucoooo** [comment]
> If you are using pnpm, you may need to add an additional file. [refer to](https://github.com/element-plus/element-plus-nuxt-starter/blob/main/.npmrc)
> 
> // .npmrc
> 
> ```
> shamefully-hoist=true
> ```
> 
> then `pnpm i`

不起作用，依旧报错
