### ISSUE TITLE
Wrong url from nuxt.com

### ISSUE THREAD

**Issue by wazolab** [element-plus/element-plus-nuxt#115]
![image](https://github.com/user-attachments/assets/6543e008-615d-45aa-a42f-068d27f39de1)
Source: https://nuxt.com/modules/element-plus

The link redirects to Element Plus repo: https://github.com/element-plus/element-plus instead of this repo.

**Comment by tolking** [comment]
It seems that the issues is caused by [nuxt modules L6](https://github.com/nuxt/modules/blob/main/modules/element-plus.yml#L6).

If you are interested, you can try fixing it.

**Comment by wazolab** [comment]
To be followed here: https://github.com/nuxt/modules/issues/1051
