### ISSUE TITLE
[Component] [time-picker] time-picker relies on dayjs exceptions

### ISSUE THREAD

**Issue by SupGiant** [element-plus/element-plus-nuxt#118]
Bug Type: Component

## Environment
- nuxt: `^3.12.4`
- @element-plus/nuxt: `^1.0.10`
- element-plus: `^2.8.1`

### Reproduction Link

[GitHub repository](https://github.com/SupGiant/nuxt-study.git)

### Steps to reproduce
```
git clone https://github.com/SupGiant/nuxt-study.git
cd nuxt-study
pnpm install
npm run dev
```
### What is Expected?
The browser console prompts:
```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/dayjs@1.11.13/node_modules/dayjs/dayjs.min.js?v=f4ccee87' does not provide an export named 'default' (at utils.mjs?v=f4ccee87:1:8)
```
and Nuxt devtool cannot startup

### What is actually happening?

no errors, i need nuxt devtool

**Comment by melrefaie** [comment]
same issue 
Uncaught (in promise) SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/dayjs@1.11.13/node_modules/dayjs/dayjs.min.js?v=5cd8487c' does not provide an export named 'default' (at utils.mjs?v=5cd8487c:1:8)

**Comment by tolking** [comment]
link #113
