### ISSUE TITLE
 element-plus 样式没有按需加载

### ISSUE THREAD

**Issue by 1weidong** [element-plus/element-plus-nuxt#127]
`vitePluginImp({
        libList: [
          {
            libName: 'element-plus',
            libDirectory: 'es/components',
            nameFormatter: (name) => {
              return name.replace('el-', '')
            },
            style: (name) => {
              if (['el-config-provider', 'effect'].includes(name)) return false
              return `element-plus/es/components/${name.replace('el-', '')}/style/css.mjs`
            },
          },
        ]
      `}``

样式没有按需加载

**Comment by tolking** [comment]
这里不是 vitePluginImp ，你反馈错仓库了
