### ISSUE TITLE
Nuxt3 SSR模式下暗黑模式不生效

### ISSUE THREAD

**Issue by huoliwei** [element-plus/element-plus-nuxt#129]
"nuxt": "^3.13.0",
"@element-plus/nuxt": "^1.0.10",
我再nuxt.config中配置了黑色主题，但是并不生效，生成的html标签中没有class=“dark”的样式，手动添加class=“dark”后有效果

**Comment by tolking** [comment]
nuxt 中的配置只是引入样式，具体的主题展示需要自己根据情况实现
