### ISSUE TITLE
Can't set components size globally 

### ISSUE THREAD

**Issue by koptelovav** [element-plus/element-plus-nuxt#130]
I couldn't find a size option in element-plus-nuxt documentation to set components size globally.
When I user pure Vue I can set size like this:
```
app.use(ElementPlus, { size: 'small' })
```
But I can't do the same with the plugin. How I can pass the option?

**Comment by tolking** [comment]
[config-provider](https://element-plus.org/en-US/component/config-provider.html)

**Comment by koptelovav** [comment]
I stil can't use [config-provider](https://element-plus.org/en-US/component/config-provider.html). Could you release the feature?
