### ISSUE TITLE
is there a way to only import specific components

### ISSUE THREAD

**Issue by eduardotang** [element-plus/element-plus-nuxt#133]

**Comment by tolking** [comment]
It seems unnecessary to do so, as only used components will be included during build

**Comment by eduardotang** [comment]
but it seems it included all in dev server (start with nuxi dev)

**Comment by tolking** [comment]
It's like this, mainly about Nuxt generating types, auto imports, and other related code. If it is excluded, these components cannot be used in the project

**Comment by eduardotang** [comment]
is it possible to do something like https://github.com/vueComponent/ant-design-vue-nuxt/pull/67

**Comment by tolking** [comment]
I understand the issue you mentioned, and I will fix it soon.
