### ISSUE TITLE
Pre-transform error: [sass] Undefined function. 

### ISSUE THREAD

**Issue by nd2024** [element-plus/element-plus-nuxt#137]
Nuxt Version: **3.14.159**
ElementPlusNuxt Version: **1.1.0**

![image](https://github.com/user-attachments/assets/a2ae3e4b-cea7-468c-aa4d-524df454aeb3)

**Comment by tolking** [comment]
update the dependency version？

"sass": "^1.79.3",

**Comment by nd2024** [comment]
yes, I already solved it. Thanks anyway
