### ISSUE TITLE
在nuxt3中使用Dialog和Message时，Message会被Dialog遮罩层覆盖；z-index没有按照预期增加，层级不共享

### ISSUE THREAD

**Issue by esoon697** [element-plus/element-plus-nuxt#138]
# 问题描述

在nuxt3中使用Dialog和Message时，先弹出Dialog弹窗再调用Message；Message会被Dialog遮罩层覆盖；z-index没有按照预期增加，层级不共享。
理想情况下应该是，Message在Dialog的上层，z-index按照调用先后共享递增。

---

## 环境信息

- **操作系统**: Windows 11
- **运行环境/浏览器版本**: Chrome 116, Node.js 18.19.1

---

## 重现步骤

1. [步骤一] Dialog弹窗可见性设置为true
2. [步骤二] 点击弹窗中的任意按钮，弹出Message

---

## 预期行为

Message浮动在Dialog的上层

---

## 实际行为

Message会被Dialog遮罩层覆盖，Message的z-index从默认index开始递增

---

## 截图或日志

- ![image](https://github.com/user-attachments/assets/5e91cdb8-f680-4d37-bf12-5a9042c257cf)
- ![image](https://github.com/user-attachments/assets/689d31c8-110b-49c7-8645-28e5ea772a7e)

---

## 相关链接

---

**Comment by gjfei** [comment]
同样发现这个问题

**Comment by Zhang-Wei-666** [comment]
我也是这个问题, 这是复现:
https://github.com/Zhang-Wei-666/element-plus-bug-report/tree/2

**Comment by tolking** [comment]
我似乎找到问题了，如果有时间可以帮忙测试下。

向 nuxt.config.ts 配置文件中增加配置

``` ts
export default defineNuxtConfig({
  vite:{
    optimizeDeps: {
      exclude: ['element-plus']
    }
  },
}
```

**Comment by Zhang-Wei-666** [comment]
> 我似乎找到问题了，如果有时间可以帮忙测试下。
> 
> 向 nuxt.config.ts 配置文件中增加配置
> 
> ```ts
> export default defineNuxtConfig({
>   vite:{
>     optimizeDeps: {
>       exclude: ['element-plus']
>     }
>   },
> }
> ```

我试过了, 可行, 加上后正常了

**Comment by lihxhit** [comment]
加上后还不正常怎么办

**Comment by Zhang-Wei-666** [comment]
你看下你项目的 .lock 文件, 是不是有两个不同的 `element-plus` 依赖

**Comment by lihxhit** [comment]
没有。。。
