### ISSUE TITLE
ElMessageBox not working

### ISSUE THREAD

**Issue by VandrerenErik** [element-plus/element-plus-nuxt#27]
Everything seems to work just fine except ElMessageBox and I don't find anything relevant in the console or anywhere else. See image for reference:

**Update**: it seems like the styles are the only thing not being loaded.

Top left corner, broken:
![image](https://user-images.githubusercontent.com/54407345/212659248-837c5da3-efda-4d85-88cd-6b26a37b13a7.png)

**Comment by tolking** [comment]
It looks like a RegExp error, the ElMessageBox is matched to ElMessage.

**Comment by VandrerenErik** [comment]
That was a very quick fix @tolking, cheers for that!
