### ISSUE TITLE
CSS for severals components not loading

### ISSUE THREAD

**Issue by cawa-93** [element-plus/element-plus-nuxt#37]
Reproduction may be found here: https://github.com/olena195/blog_kyivska_zefirka/tree/el-issues
![зображення](https://user-images.githubusercontent.com/1662812/218145061-9dab8ff5-335f-41c6-bbf4-02d0236d3e5b.png)
Side menu as example. Components itself seems works. I noticed that css not loaded if el-components used inside my own components. If I use it dirrectly in `page` then all fine

**Comment by tolking** [comment]
[SiteMenu.vue](https://github.com/olena195/blog_kyivska_zefirka/blob/el-issues/components/SiteMenu.vue#L3)

```diff
- import { computed, fetchContentNavigation, useAsyncData } from "#imports";
- import { ElMenu, ElMenuItem, ElSubMenu } from "element-plus";
```

You do not need to import these components by manually, Nuxt will imports them automatically.

When components are imported directly from element-plus, Nuxt will consider that these components do not need to be imported automatically. And of course, this module will not automatically load the style of components.

Refer to [Nuxt document](https://nuxt.com/docs/guide/directory-structure/components#direct-imports), and [element-plus-nuxt-starter](https://github.com/element-plus/element-plus-nuxt-starter)
