### ISSUE TITLE
Cannot find package 'element-plus' imported from

### ISSUE THREAD

**Issue by Rain-Hsiang** [element-plus/element-plus-nuxt#40]
in nuxt3, add element-plus/nuxt , get error
//  在nuxt3中，根据文档安装配置后
[nuxt3](https://nuxt.com/docs/getting-started/installation)  
```
npx nuxi init project-name
yarn
```
[Element-Plus](https://nuxt.com/modules/element-plus) 
```
yarn add @element-plus/nuxt -D
```
```ts
// nuxt.config.ts
export default defineNuxtConfig({
  modules: [
    '@element-plus/nuxt'
  ],
  elementPlus: { /** Options */ }
})
```
Get Error：
```vue
// ' ERROR  Cannot start nuxt:  Cannot find package 'element-plus' imported 
// from  /Users/rain/Desktop/nuxt3-app 2/node_modules/@element-plus/nuxt/dist/module.mjs'
```
node：v18.14.0
yarn：1.22.19
npm：9.3.1
package.json
```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@element-plus/nuxt": "1.0.3",
    "nuxt": "^3.2.2"
  }
}
```

But,[element-plus-nuxt-starter](https://github.com/element-plus/element-plus-nuxt-starter) can run

**Comment by Rain-Hsiang** [comment]
But  !!!!!!!!!!!! 
use `npm` 
Wait a long long long long time
it`s Normal.
why ?
how to `yarn`

**Comment by tolking** [comment]
Link #26, #31

**Comment by tolking** [comment]
Link #26, #31

**Comment by Rain-Hsiang** [comment]
> But !!!!!!!!!!!! use `npm` Wait a long long long long time its Normal. why ? how to `yarn`
need install element-plus  ......😒
