### ISSUE TITLE
server-side does not render <el-table>

### ISSUE THREAD

**Issue by MyNine** [element-plus/element-plus-nuxt#42]
other elements are returned by server side, but only 'el-table' was not rendered and returned from server side;

![image](https://user-images.githubusercontent.com/15926435/221410902-43050726-2d38-4c72-ba51-b62d6ff138d3.png)

**Comment by tolking** [comment]
Can you provide a simple demo that can be reproduced?

**Comment by MyNine** [comment]
i have got it,  table doesn't support ssr
![image](https://user-images.githubusercontent.com/15926435/221447561-a201398c-7132-443d-977e-a6390d5e9532.png)

**Comment by sergdevguy** [comment]
Hello. The table still doesn't render its contents statically after generation?
As I understand it, this problem is not a priority now?

**Comment by tolking** [comment]
It is currently quite complicated to modify the Table component to render all content on the server side. As far as I know, no one is working on this yet.
