### ISSUE TITLE
How to use with nuxt/i18n?

### ISSUE THREAD

**Issue by AnzhiZhang** [element-plus/element-plus-nuxt#43]
How to use element plus with [Nuxt I18n](https://v8.i18n.nuxtjs.org)?

The documentation only provides a way to set a permanent locale, but it cannot be switched reactively: https://element-plus.org/en-US/guide/i18n.html#configprovider

Is there a way, like in Element UI, to set an i18n function for Element Plus?

```js
Vue.use(Element, {
  i18n: (key, value) => app.i18n.t(key, value)
});
```

**Comment by tolking** [comment]
Is not a demo of switching languages already provided in the document? [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1idXR0b24gbWItMiBAY2xpY2s9XCJ0b2dnbGVcIj5Td2l0Y2ggTGFuZ3VhZ2U8L2VsLWJ1dHRvbj5cbiAgICA8YnIgLz5cblxuICAgIDxlbC1jb25maWctcHJvdmlkZXIgOmxvY2FsZT1cImxvY2FsZVwiPlxuICAgICAgPGVsLXRhYmxlIG1iLTEgOmRhdGE9XCJbXVwiIC8+XG4gICAgICA8ZWwtcGFnaW5hdGlvbiA6dG90YWw9XCIxMDBcIiAvPlxuICAgIDwvZWwtY29uZmlnLXByb3ZpZGVyPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBjb21wdXRlZCwgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHpoQ24gZnJvbSAnZWxlbWVudC1wbHVzL2Rpc3QvbG9jYWxlL3poLWNuLm1qcydcbmltcG9ydCBlbiBmcm9tICdlbGVtZW50LXBsdXMvZGlzdC9sb2NhbGUvZW4ubWpzJ1xuXG5jb25zdCBsYW5ndWFnZSA9IHJlZignemgtY24nKVxuY29uc3QgbG9jYWxlID0gY29tcHV0ZWQoKCkgPT4gKGxhbmd1YWdlLnZhbHVlID09PSAnemgtY24nID8gemhDbiA6IGVuKSlcblxuY29uc3QgdG9nZ2xlID0gKCkgPT4ge1xuICBsYW5ndWFnZS52YWx1ZSA9IGxhbmd1YWdlLnZhbHVlID09PSAnemgtY24nID8gJ2VuJyA6ICd6aC1jbidcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by AnzhiZhang** [comment]
I am concerned that `ElConfigProvider` is not a good practice, it has to be added at the layout or app level to avoid adding it once for each use of the component.

It would introduce more performance overhead and an unnecessary layer of global components than injecting a function. In the old internationalization practice, I only had to provide the language of the element to vuei18n, but now I need to handle it separately.

---

### locale messages for old practice

en file for vuei18n
```js
import elementUILocale from "element-ui/lib/locale/lang/en";

export default {
  ...elementUILocale,
}
```

zh file for vuei18n
```js
import elementUILocale from "element-ui/lib/locale/lang/zh-CN";

export default {
  ...elementUILocale,
}
```

### locale messages for new practice
in **app.vue**
```js
<script setup>
import enUS from "element-plus/lib/locale/lang/en";
import zhCN from "element-plus/lib/locale/lang/zh-cn";

const i18n = useI18n();
const locale = computed(
    () => (
        {
          "en-US": enUS,
          "zh-CN": zhCN,
        }[i18n.locale.value]
    )
);
</script>
```

---

The comparison shows that this is not a good practice for centralized integration of i18n in an app, the app's i18n and element ui's i18n are in different way, if more packages do this, the maintainability will drop dramatically and there will be more layers of some `ConfigProvider` in `app.vue` or layouts.

**Comment by tolking** [comment]
I remember that `[i18n](i18n: (key, value) => app.i18n.t(key, value))` was supported in earlier versions, but a later version removed the relevant api. You can search for it yourself.

**Comment by AnzhiZhang** [comment]
I found that it was supported in element-plus/element-plus#1306 to mix element-plus messages with app locales, but removed in element-plus/element-plus#3016, what is the reason to do that change?

And there is still a `Translator` exists but cannot be set, https://github.com/element-plus/element-plus/blob/dev/packages/hooks/use-locale/index.ts. Why don't provide an config or injection of Translator to integrate and compatible with vueI18n?

**Comment by tolking** [comment]
There were many issues with i18n before, and now this should be to avoid compatibility errors.

Perhaps you should now consider using ElConfigProvider component to achieve i18n.
