### ISSUE TITLE
nuxt components highlighting is not work when i use this plugin

### ISSUE THREAD

**Issue by weiyidechicheng** [element-plus/element-plus-nuxt#46]
// components dir
components
   -- Test.vue
   -- Test2.vue

// app.vue
```vue
  <Test />   <!-- not highlighting  -->
  <Test2 />    <!-- not highlighting  -->
  <ElButton type="success">button</ElButton>   <!-- highlighting  -->
  <LazyElButton type="warning">lazy button</LazyElButton>   <!-- not highlighting  -->
```

when I remove this plugin, nuxt highlighting work very well.

**Comment by weiyidechicheng** [comment]
![](https://gitee.com/hwj171/easy-project11/blob/master/public/Snipaste_2023-03-13_00-20-45.png)

**Comment by tolking** [comment]
This is just a Nuxt module. It has no ability to affect your editor display.

**Comment by weiyidechicheng** [comment]
> This is just a Nuxt module. It has no ability to affect your editor display.
> 
> Or you can provide more information

Thank you,I know what has caused this problem.I should not  configure `tsconfig.json` with `"types": ["element-plus/global"]` as element-plus document says.
