### ISSUE TITLE
Options 中的 Components 选项无法正常使用

### ISSUE THREAD

**Issue by bhaoo** [element-plus/element-plus-nuxt#49]
如标题所说，我在 [element-plus-nuxt-starter](https://github.com/element-plus/element-plus-nuxt-starter) 项目中的 `nuxt.config.ts` 写入以下内容：
```ts
elementPlus: {
    components: ['ElAvatar'],
},
```
但我发现当 nuxt 重载配置时并不会自动载入 ElAvatar 组件对应的样式内容
![](https://cnn.hd-r.cn/de2c902c60aaa8a43d9ceab4a36401dd.png)

**Comment by tolking** [comment]
组件和样式是自动引入的，只有使用的组件才会引入。

**Comment by bhaoo** [comment]
无法通过 Options 导入未使用过的组件吗？

**Comment by bhaoo** [comment]
> A list of imports that need to be automatically imported externally.
> 
> @default
> 
>  ['ElLoading', 'ElMessage', 'ElMessageBox', 'ElNotification']
> When you need to add automatically import content from Element Plus, you can add it here.

那 imports 属性和文档说明也不符了哇（悲

**Comment by tolking** [comment]
增加到 imports 列表只是不用写 `import { xx } from 'element-plus'`

一样的，只有使用才会加载

**Comment by bhaoo** [comment]
好的 谢谢力
