### ISSUE TITLE
自动配置 rollupConfig 以规避 Cannot find package '@popperjs/core' 错误

### ISSUE THREAD

**Issue by everyx** [element-plus/element-plus-nuxt#51]
详见 element-plus/element-plus#10979 ，其中 https://github.com/element-plus/element-plus/issues/10979#issuecomment-1473107778 提供了规避方案，是否可以集成到该 module 中？

```js
import {nodeResolve} from "@rollup/plugin-node-resolve";

export default defineNuxtConfig({
    nitro: {
        rollupConfig: {
            // @ts-ignore
            plugins: [
                nodeResolve({exportConditions: ['node']}),
            ],
        },
    },
});
```

**Comment by tolking** [comment]
暂未计划

这个方案仅适用于 Vite，不适用于 webpack

**Comment by AnzhiZhang** [comment]
在 nuxt 更新到 3.4.3 后，该方案似乎失效了

**Comment by AnzhiZhang** [comment]
Nuxt 3.4 之后加上这个就好了
add this into `package.json` after Nuxt 3.4

```
    "@popperjs/core": "npm:@sxzz/popperjs-es@^2.11.7",
```

**Comment by everyx** [comment]
设置 `node-linker=hoisted` 也可以


`.npmrc`:

```ini
node-linker=hoisted
```

**Comment by AnzhiZhang** [comment]
> ```ini
> node-linker=hoisted
> ```

删除 `package-lock.json`，node_modules 后重新 install，无效

**Comment by everyx** [comment]
> > ```ini
> > node-linker=hoisted
> > ```
> 
> 删除 `package-lock.json`，node_modules 后重新 install，无效

我用的是 `pnpm`，并且未开启 `shamefully-hoist`

**Comment by AnzhiZhang** [comment]
> 

npm 是没有用的
