### ISSUE TITLE
Suffix-icon with input not working

### ISSUE THREAD

**Issue by vitjaz** [element-plus/element-plus-nuxt#53]
![image](https://user-images.githubusercontent.com/47814045/234876928-9b71b799-13cd-4b8f-90d3-f70cd55be7a1.png)

Icon from element lib not showing and not importing. What am I doing wrong?

How can I use my own svg icons in suffix/prefix?

**Comment by tolking** [comment]
Calendar -> ElIconCalendar

**Comment by vitjaz** [comment]
@tolking thanks! Can you help me with second question?
_How can I use my own svg icons in suffix/prefix?_

**Comment by tolking** [comment]
> suffix-icon | suffix icon component | string / **Component**
