### ISSUE TITLE
element-plus component "steps" lagging or taking taking time to load 

### ISSUE THREAD

**Issue by Abeni001** [element-plus/element-plus-nuxt#59]
I were using element-plus' steps for my sign up pages, when I try it to run it take too much time to render or load.
  <el-steps :active="active" finish-status="success" class="pb-4 mb-2">
                <el-step />
                <el-step />
                <el-step />
                <el-step />
      </el-steps>
![step delay](https://github.com/element-plus/element-plus-nuxt/assets/103540341/8d6c6e9c-339c-4b55-a234-cece5212e653)

**Comment by tolking** [comment]
This `Steps` component requires collecting slot config on the client side, so it cannot be fully rendered on the server side.

This may be the cause of the problem
