### ISSUE TITLE
Cannot find module 'element-plus/es/component'

### ISSUE THREAD

**Issue by MoLing-Dong** [element-plus/element-plus-nuxt#60]
Error while requiring module @element-plus/nuxt: Error: Cannot find module 'element-plus/es/component'                                                                                                        00:05:06  
Require stack:

**Comment by tolking** [comment]
Perhaps you should check if the `element-plus` component library is installed

**Comment by MoLing-Dong** [comment]
> Perhaps you should check if the `element-plus` component library is installed

I installed it, and this error pops up after I install something else with yarn, and then I have to reinstall it with npm install before I can start the project

**Comment by zy94xhn** [comment]
are you resolve it？

**Comment by pocketChao** [comment]
麻烦问下 yarn
解决了吗

**Comment by tolking** [comment]
抱歉我没有使用yarn，我使用pnpm完全正常。

你可以检查下相关配置，例如

```
// .npmrc
shamefully-hoist=true
```

**Comment by zy94xhn** [comment]
> 麻烦问下 yarn 解决了吗

已解决。 需要安装element-plus和@popperjs/core

**Comment by pocketChao** [comment]
> 抱歉我没有使用yarn，我使用pnpm完全正常。
> 
> 你可以检查下相关配置，例如
> 
> ```
> // .npmrc
> shamefully-hoist=true
> ```

我只有window会有这样的问题 在我的mac设备里可以跑起来。。

**Comment by wodepig** [comment]
same question
1 . yarn remove  @element-plus/nuxt
2. npm install -D @element-plus/nuxt
3. npm run dev
run success

**Comment by DeanWade9** [comment]
> same question 1 . yarn remove @element-plus/nuxt 2. npm install -D @element-plus/nuxt 3. npm run dev run success

thank you, worked fine for me!
