### ISSUE TITLE
There will still be hydration errors

### ISSUE THREAD

**Issue by game428** [element-plus/element-plus-nuxt#64]
![image](https://github.com/element-plus/element-plus-nuxt/assets/26991278/e46f3dc8-40a2-4864-83bc-1f279f980d91)
![image](https://github.com/element-plus/element-plus-nuxt/assets/26991278/0185a36d-409b-4774-aea6-ece2f16c82d7)
Does element-plus-nuxt not handle it, or does it need additional configuration?

**Comment by tolking** [comment]
Can you provide a minimum reproducible demo?

**Comment by game428** [comment]
> Can you provide a minimum reproducible demo?

![image](https://github.com/element-plus/element-plus-nuxt/assets/26991278/b622fb37-4864-4500-8b5b-51859b3eca74)
![image](https://github.com/element-plus/element-plus-nuxt/assets/26991278/3a2ee437-7610-4368-ba6f-8a078e4fc138)

**Comment by game428** [comment]
???

> Can you provide a minimum reproducible demo?

**Comment by tolking** [comment]
Sorry,  I am unable to reproduce your issue
