### ISSUE TITLE
one component have been render twice

### ISSUE THREAD

**Issue by 21stc-09** [element-plus/element-plus-nuxt#67]
when i change the nuxt project file directory，i found this mistake
in the nuxt default layout (src/layouts/default.vue), i just **use one foot component** but **render two same foot component**
i found this is because of the **el-drawer** in **app.vue**

reappearance：
https://codesandbox.io/p/sandbox/boring-hugle-s99q27?file=%2Fsrc%2Fapp.vue%3A15%2C16

**Comment by tolking** [comment]
It seems that the hydration error was caused by Teleport, You can configure `append-to-body` for el-drawer.
