### ISSUE TITLE
外部引用el-config-provider无效

### ISSUE THREAD

**Issue by CheeseUnknown** [element-plus/element-plus-nuxt#71]
项目概述：
有一个nuxt-layer，发布在npm上，另一个项目使用extends引用。

问题描述：
在nuxt-layer中设置el-config-provider，在该项目中是有效的。但在另一个项目引用的时候，当项目中有el-config-provider时，nuxt-layer中所有的el-config-provider配置全部失效，在项目中设置el-config-provider也无法影响nuxt-layer中的。

**Comment by tolking** [comment]
既然能够在第一个项目中使用，似乎和当前项目没有关系。
问题的原因很可能是你第二个项目中依赖不同的element-plus引起的

**Comment by CheeseUnknown** [comment]
> 既然能够在第一个项目中使用，似乎和当前项目没有关系。 问题的原因很可能是你第二个项目中依赖不同的element-plus引起的

似乎是这个问题，我该如何排查？项目的element-plus都是由引用的项目提供，按道理应该是同一个element-plus吧

**Comment by CheeseUnknown** [comment]
在引入项目的nuxt.config.ts中的vite.optimizeDeps.exclude添加'element-plus'就修复了这个问题
