### ISSUE TITLE
How about move "element-plus" from the "devDependencies" to the "dependencies"?

### ISSUE THREAD

**Issue by BluesYoung-web** [element-plus/element-plus-nuxt#72]
When i install this package by @nuxt/devtools, it will interrupt

![image](https://github.com/element-plus/element-plus-nuxt/assets/55608642/77a4f49f-0315-4ab9-aee2-135009c897df)

How about move "element-plus" from the "devDependencies" to the "dependencies", just like the @unocss/nuxt

![image](https://github.com/element-plus/element-plus-nuxt/assets/55608642/5e295410-c75b-4d8b-9d33-2a5db2408c0a)

**Comment by tolking** [comment]
This may not be a good idea, as the modified project may reference different ElementsPlus and result in errors

**Comment by BluesYoung-web** [comment]
> This may not be a good idea, as the modified project may reference different ElementsPlus and result in errors

Why not move this repo into the element-plus's monorepo, and then the reference will not be a problem

**Comment by tolking** [comment]
This also need to make the dependency versions to maintain a consistent
