### ISSUE TITLE
Component styles are not auto-imported

### ISSUE THREAD

**Issue by Maiquu** [element-plus/element-plus-nuxt#73]
## Issue

When components are auto-imported, their respective styles are not auto-imported.

## Potential Cause

[@vitejs/plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue) changed how it transforms `.vue` files which causes [transformPlugin](https://github.com/element-plus/element-plus-nuxt/blob/main/src/core/transformPlugin.ts) unable to detect the `element-plus` components. 

How vue plugin currently transforms `.vue` files:

![Transform Stack for vue](https://github.com/element-plus/element-plus-nuxt/assets/37181247/d2fd065b-1676-4573-8b3b-56ddbfab355a)

`element-plus` module does not perform any transformation according to the following stack:

![Transform Stack for element-plus](https://github.com/element-plus/element-plus-nuxt/assets/37181247/f0d02791-c659-4cbf-9293-6417d98f0eb8)

**Comment by Maiquu** [comment]
It's caused by importing the component directly. If its working as intended, feel free to close the issue.

**Comment by tolking** [comment]
Directly importing components will not automatically import styles, which is consistent with Nuxt's official behavior
