### ISSUE TITLE
`element-plus-nuxt`  triggering so much reloading on dev in `nuxt 3.8.2`

### ISSUE THREAD

**Issue by gyhyfj** [element-plus/element-plus-nuxt#80]
Because of the auto-import feature of `element-plus-nuxt` in `nuxt 3.8.2`, this plugin always triggers a lot of reloading during development, especially when navigating to a new page. I spend a lot of time waiting for reloads, and what's worse, if there are syntax errors on that page I am navigating to, I can never reach that page, and errors are not displayed in the terminal.

I believe Nuxt should address this issue, but, could the auto-import feature become an optional configuration for `element-plus-nuxt` users during development to load the entire Element Plus library?

```bash
[18:32:37] ℹ ✨ new dependencies optimized: element-plus/es/components/message/style/css, wujie, element-plus/es/components/input/index, ele
ment-plus/es/components/form/index, element-plus/es/components/checkbox/index, element-plus/es/components/input/style/css, element-plus/es/components/form-item/style/css, element-plus/es/components/form/style/css, element-plus/es/components/checkbox/style/css, nanoid
ℹ ✨ optimized dependencies changed. reloading                                                                                  18:32:37
[18:32:53] ℹ ✨ new dependencies optimized: rxjs, element-plus/es/components/select/index, element-plus/es/components/button/index, element-
plus/es/components/collapse/index, element-plus/es/components/option/style/css, element-plus/es/components/select/style/css, element-plus/es/components/button/style/css, element-plus/es/components/collapse-item/style/css, element-plus/es/components/collapse/style/css, element-plus/es/components/loading/style/css, element-plus/es/components/slider/index, element-plus/es/components/slider/style/css, element-plus/es/components/popover/index, element-plus/es/components/dialog/index, element-plus/es/components/popover/style/css, element-plus/es/components/dialog/style/css, element-plus/es/components/tooltip/index, element-plus/es/components/tooltip/style/css, element-plus/es/components/message-box/style/css, element-plus/es/components/icon/index, element-plus/es/components/icon/style/css, konva, element-plus/es/components/carousel/index, element-plus/es/components/carousel-item/style/css, element-plus/es/components/carousel/style/css
ℹ ✨ optimized dependencies changed. reloading                                                                                  18:32:53    
[18:34:06] ℹ ✨ new dependencies optimized: element-plus/es/components/date-picker/index, element-plus/es/components/dropdown/index, element
-plus/es/components/pagination/index, element-plus/es/components/date-picker/style/css, element-plus/es/components/dropdown-item/style/css, element-plus/es/components/dropdown-menu/style/css, element-plus/es/components/dropdown/style/css, element-plus/es/components/pagination/style/css, dayjs
ℹ ✨ optimized dependencies changed. reloading                                                                                  18:34:06
```

**Comment by guipie** [comment]
me too
![image](https://github.com/element-plus/element-plus-nuxt/assets/55727172/5b574324-6bd6-4b2e-848e-37138529d1a7)

**Comment by gyhyfj** [comment]
See https://github.com/nuxt/nuxt/issues/24196 , my temp solution is add this to `nuxt.config.ts`:

> me too ![image](https://private-user-images.githubusercontent.com/55727172/289930874-5b574324-6bd6-4b2e-848e-37138529d1a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzQyMTQsIm5iZiI6MTcwMjQzMzkxNCwicGF0aCI6Ii81NTcyNzE3Mi8yODk5MzA4NzQtNWI1NzQzMjQtNmJkNi00YjJlLTg0OGUtMzcxMzg1MjlkMWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAyMTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OGE0M2U5NWZiZGY2MTZlMjhlNmMzMWQzYTczMTMxMzcxNmQ3ZGUxNjc3YTRkNDgxYmNiMmQyNzg2ZTc3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8EUjV33sPL7sV8AOgZi1PSzm9hU6pBi9BH3q2F_4Ij4)

**Comment by guipie** [comment]
> See [nuxt/nuxt#24196](https://github.com/nuxt/nuxt/issues/24196) , my temporary solution is adding this to `nuxt.config.ts`:
> 
> ```ts
>   vite: {
>     optimizeDeps: {
>       include: ['element-plus/es/components/**'],
>     },
>   },
> ```
> 
> > me too ![image](https://private-user-images.githubusercontent.com/55727172/289930874-5b574324-6bd6-4b2e-848e-37138529d1a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzQyMTQsIm5iZiI6MTcwMjQzMzkxNCwicGF0aCI6Ii81NTcyNzE3Mi8yODk5MzA4NzQtNWI1NzQzMjQtNmJkNi00YjJlLTg0OGUtMzcxMzg1MjlkMWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAyMTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OGE0M2U5NWZiZGY2MTZlMjhlNmMzMWQzYTczMTMxMzcxNmQ3ZGUxNjc3YTRkNDgxYmNiMmQyNzg2ZTc3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8EUjV33sPL7sV8AOgZi1PSzm9hU6pBi9BH3q2F_4Ij4)


After adding this, a new problem occurred, the home page loaded very slowly

![1702459730128](https://github.com/element-plus/element-plus-nuxt/assets/55727172/e3187500-128c-4ab3-8dc1-5de9dc250b47)

**Comment by tolking** [comment]
How about this?

```ts
vite: {
    optimizeDeps: {
      include: [
        'element-plus/es/components/*/index',
        'element-plus/es/components/*/style/index', // or 'element-plus/es/components/*/style/css'
      ],
    },
},
```

**Comment by tolking** [comment]
After updating to the latest version (1.0.10), the reloading issue will be optimized, at the cost of a significant increase in the number of requests. You can choose to update according to the situation.
