### ISSUE TITLE
自动导入了没用到的组件文件，如何配置？

### ISSUE THREAD

**Issue by HWYD** [element-plus/element-plus-nuxt#83]
没有用到的组件，js和css文件也自动导入了，怎么设置按需导入，没用到的不导入呢？例如没有用到el-badge组件，但还是导入了相关文件
![image](https://github.com/element-plus/element-plus-nuxt/assets/52754591/52b705a9-840b-4acf-8fd8-1a746c4fcec6)

**Comment by tolking** [comment]
有没有可能是你使用的组件内部使用了 ElBadge

**Comment by tolking** [comment]
有没有可能是你使用的组件内部使用了 ElBadge
