### ISSUE TITLE
an error occured using nuxt3 + element plus when i try to deploy it 

### ISSUE THREAD

**Issue by SheikhElMoctarG** [element-plus/element-plus-nuxt#84]
I'm using Nuxt3 in my project, i added elementplus for add some features, but i founded some problems when I tried to deploy it on vercel and building.

`
ERROR  Error while requiring module @element-plus/nuxt: TypeError: _dayjs.default.extend is not a function                                                                                                   

`
what is the solution ?

**Comment by tolking** [comment]
Same like [#8165](https://github.com/element-plus/element-plus/issues/8165).

There is currently no stable reproduction of this issue. Maybe you can try reinstalling the dependencies, or use yarn or pnpm.

Of course, we also welcome you to provide an example that can reproduce the issues
