### ISSUE TITLE
【datepicker】 dayjs 引入时发生错误

### ISSUE THREAD

**Issue by lin52025iq** [element-plus/element-plus-nuxt#87]
<img width="1425" alt="image" src="https://github.com/element-plus/element-plus-nuxt/assets/87741822/efe957fc-7aad-4760-bfcb-83aaf6184eab">

<img width="1434" alt="image" src="https://github.com/element-plus/element-plus-nuxt/assets/87741822/57a4779b-cd53-45c2-94a6-c7b5f2835762">

可以通过编译，但在浏览器上提示图上的错误。

* @element-plus/nuxt: ^1.0.7
* element-plus: 2.6.0
* vue: 3.4.21
* nuxt: ^3.10.3

**Comment by tolking** [comment]
与 #84 重复

这个问题需要一个可以复现的示例

**Comment by orczh-hj** [comment]
我也遇到这个问题，可能是所依赖的dayjs提供的是CommonJS模块，导致导入出错，但是这个问题怎么解决呢？
