### ISSUE TITLE
npm ERR! notarget No matching version found for nuxi@^3.11.0.

### ISSUE THREAD

**Issue by ziyu-93** [element-plus/element-plus-nuxt#90]
npm ERR! notarget No matching version found for nuxi@^3.11.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

83 silly fetch manifest nuxi@^3.11.0

nuxi   "latest": "3.10.1"
https://repo.huaweicloud.com/repository/npm/nuxi

npm install error

#88

**Comment by tolking** [comment]
You can add config to solve the issue of #88

```ts
export default defineNuxtConfig({
  modules: [
    '@element-plus/nuxt'
  ],
  elementPlus: {
    subComponents: {
      ElAnchor: ['ElAnchorLink'],
      ElTour: ['ElTourStep']
    }
  }
})
```

**Comment by tolking** [comment]
[npm](https://www.npmjs.com/package/nuxi/v/3.11.0)
