### ISSUE TITLE
Error while requiring module @element-plus/nuxt: TypeError: _dayjs.default.extend is not a function

### ISSUE THREAD

**Issue by JL-Code** [element-plus/element-plus-nuxt#95]
` ERROR  _dayjs.default.extend is not a function                                                                                                       22:54:35

  at node_modules/element-plus/es/components/time-picker/src/time-picker.mjs:10:16
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at node_modules/element-plus/es/components/time-picker/index.mjs:1:2184
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at node_modules/element-plus/es/components/calendar/src/date-table.mjs:2:1
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at node_modules/element-plus/es/components/calendar/src/date-table2.mjs:3:18 `

```json
{
"devDependencies": {
    "@element-plus/icons-vue": "^2.3.1",
    "@element-plus/nuxt": "^1.0.7",
    "@heroicons/vue": "^2.1.1",
    "@livechat/widget-vue": "^1.3.2",
    "@nuxt/devtools": "^1.0.6",
    "@nuxt/image": "^1.2.0",
    "@nuxt/types": "^2.17.2",
    "@nuxt/typescript-build": "^3.0.2",
    "@nuxtjs/device": "^3.1.1",
    "@nuxtjs/google-fonts": "^3.1.3",
    "@nuxtjs/tailwindcss": "^6.10.3",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@pinia/nuxt": "^0.5.1",
    "@splidejs/splide-extension-auto-scroll": "^0.5.3",
    "@splidejs/vue-splide": "^0.6.12",
    "@tailwindcss/forms": "^0.5.7",
    "@tailwindcss/typography": "^0.5.10",
    "@types/js-cookie": "^3.0.6",
    "@types/node": "^20.10.4",
    "@types/numeral": "^2.0.5",
    "@vueuse/nuxt": "^10.7.2",
    "chalk": "^5.3.0",
    "class-variance-authority": "^0.7.0",
    "dayjs": "^1.11.10",
    "dayjs-nuxt": "^2.1.9",
    "element-plus": "^2.4.4",
    "js-cookie": "^3.0.5",
    "less": "^4.2.0",
    "md-editor-v3": "^4.9.0",
    "numeral": "^2.0.6",
    "nuxt": "^3.10.0",
    "nuxt-bugsnag": "^7.2.3",
    "nuxt-delay-hydration": "^1.3.3",
    "nuxt-gtag": "^1.1.1",
    "nuxt-headlessui": "^1.1.5",
    "oidc-client-ts": "^2.4.0",
    "pinia": "^2.0.0",
    "rollup-plugin-gzip": "^3.1.0",
    "sass": "^1.69.5",
    "typescript": "^5.3.3"
  }
}
```

**Comment by gapgag55** [comment]
Still same problem

**Comment by gapgag55** [comment]
@JL-Code element-plus v2.6.3 and element-plus/nuxt v1.0.6 was solved

**Comment by JL-Code** [comment]
> @JL-Code element-plus v2.6.3 and element-plus/nuxt v1.0.6 was solved

I used this [](https://github.com/element-plus/element-plus-nuxt-starter/blob/main/pnpm-lock.yaml)
<img width="1278" alt="image" src="https://github.com/element-plus/element-plus-nuxt/assets/14163944/a24e0c67-818b-4aaf-a1d0-7bab6455c627">

**Comment by ufvnkde7194** [comment]
same problem

**Comment by tmmsmoreira** [comment]
I am having the same problem. And is only happening using npm and not pnpm.

**Comment by trandaison** [comment]
The problem was `element-plus v2.7.0` it self.
I've run into this issue as well, for me, `@element-plus/nuxt v1.0.8` and `element-plug v2.6.3` is working.

**Comment by tolking** [comment]
try

```ts
export default defineNuxtConfig({
vite: {
    optimizeDeps: {
      include: ['dayjs', 'dayjs/plugin/*', 'element-plus']
    }
  }
})
```

**Comment by alxpereira** [comment]
Same issue, rollback to 2.6.3 was necessary

**Comment by chendaozhun** [comment]
Reproduction：
[https://codesandbox.io/p/devbox/wonderful-elion-wm8dqg?file=%2Fpackage.json%3A8%2C33](url)

**Comment by chendaozhun** [comment]
https://codesandbox.io/p/devbox/wonderful-elion-wm8dqg?file=%2Fpackage.json%3A8%2C33

**Comment by zhang20084** [comment]
同样的问题，请问解决了吗

**Comment by Ena-Heleneto** [comment]
> The problem was `element-plus v2.7.0` it self. I've run into this issue as well, for me, `@element-plus/nuxt v1.0.8` and `element-plug v2.6.3` is working.

I tried it but it doesn't work

**Comment by Ena-Heleneto** [comment]
I only have this problem in linux environment

**Comment by trandaison** [comment]
@Ena-Heleneto You are using `element-plus ^2.5.3` in `package.json`. That's mean the package manager will install the `2.x.y` with the x and y are latest (in this case, it's 2.7.0, it's not 2.5.3 as you thought). You can check which version was actually installed in lock file.

You should specify a version instead. try this:

```diff
-    "element-plus": "^2.5.3",
+    "element-plus": "2.6.3",
```

**Comment by Ena-Heleneto** [comment]
> @Ena-Heleneto You are using `element-plus ^2.5.3` in `package.json`. That's mean the package manager will install the `2.x.y` with the x and y are latest (in this case, it's 2.7.0, it's not 2.5.3 as you thought). You can check which version was actually installed in lock file.
> 
> You should specify a version instead. try this:
> 
> ```diff
> -    "element-plus": "^2.5.3",
> +    "element-plus": "2.6.3",
> ```

Yes, it worked, thank you

**Comment by houko** [comment]
直接改package.json里的文件是不生效的，默认 @element-plus/nuxt 会去安装2.7.0的element-plus
```
    "@element-plus/nuxt": "^1.0.8",
    "element-plus": "^2.6.3",
```

需要手动去执行安装一下指定版本，暂时可以解决这个问题。
```
pnpm i -D @element-plus/nuxt@=1.0.8 element-plus@=2.6.3
```
